In [1]:
import numpy as np

In [22]:
arr1 = np . arange (10) . reshape(2 , -1)
arr2 = np . repeat (1 ,10) . reshape(2 , -1)
c = np . concatenate ([ arr1 , arr2 ] , axis =1)
print('Arr1: \n', arr1)
print('Arr2: \n',arr2)
print ("Result : \n", c )

Arr1: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Arr2: 
 [[1 1 1 1 1]
 [1 1 1 1 1]]
Result : 
 [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [14]:
arr = np . array ([1 ,2 ,3])
print ( np . repeat ( arr ,3) )
print ( np . tile ( arr ,3) )

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


In [23]:
a = np . array ([2 ,6 ,1 ,9 ,10 ,3 ,27])
index = np . where ((a >=5) &( a <=10) )
print (" result ", a [ index ])

 result  [ 6  9 10]


In [24]:
def maxx (x , y ) :
    if x >= y :
        return x
    else :
        return y
a = np . array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np . array ([6 ,3 ,4 ,8 ,9 ,7 ,1])
pair_max = np . vectorize ( maxx , otypes =[ float ])
print ( pair_max (a , b ) )

[6. 7. 9. 8. 9. 7. 5.]


In [27]:
a = np . array ([5 ,7 ,9 ,8 ,6 ,4 ,5])
b = np . array ([6 ,3 ,4 ,8 ,9 ,7 ,1])

print (" Result ", np . where (a <b , b , a ) )

 Result  [6 7 9 8 9 7 5]


In [32]:
import matplotlib . image as mpimg
img = mpimg . imread('dog.jpeg')
coef = [0.21, 0.72, 0.07]
res = np.sum(np.multiply(img, coef), axis=2)

In [33]:
img.shape

(534, 800, 3)

In [37]:
res = np.average(img, axis=2)

In [41]:
res[0,0]

107.66666666666667

In [53]:
res

array([[126.23,  97.23,  90.23, ..., 159.5 , 159.5 , 159.5 ],
       [127.23,  97.23,  91.23, ..., 160.08, 159.5 , 160.08],
       [127.23,  98.23,  91.23, ..., 160.01, 159.08, 159.01],
       ...,
       [148.63, 129.49, 124.37, ..., 139.54, 136.54, 134.33],
       [141.63, 122.49, 117.44, ..., 138.89, 135.89, 134.4 ],
       [139.63, 120.49, 114.44, ..., 140.03, 137.03, 135.54]])

In [56]:
! gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: d:\MyStudy\AIO2024_Course\AIO2024_AIO-056\Module2\Week1\advertising.csv

  0%|          | 0.00/4.06k [00:00<?, ?B/s]
100%|██████████| 4.06k/4.06k [00:00<?, ?B/s]


In [57]:
import pandas as pd
df = pd . read_csv('advertising.csv')
data = df . to_numpy ()

In [70]:
keys = list(df.keys())
keys

['TV', 'Radio', 'Newspaper', 'Sales']

In [87]:
radios = data[:, keys.index('Radio')]
res = np.average(radios[radios>15])
res

32.303875968992244

In [71]:
sales = data[:, keys.index('Sales')]


In [72]:
sales

array([22.1, 10.4, 12. , 16.5, 17.9,  7.2, 11.8, 13.2,  4.8, 15.6, 12.6,
       17.4,  9.2, 13.7, 19. , 22.4, 12.5, 24.4, 11.3, 14.6, 18. , 17.5,
        5.6, 20.5,  9.7, 17. , 15. , 20.9, 18.9, 10.5, 21.4, 11.9, 13.2,
       17.4, 11.9, 17.8, 25.4, 14.7, 10.1, 21.5, 16.6, 17.1, 20.7, 17.9,
        8.5, 16.1, 10.6, 23.2, 19.8,  9.7, 16.4, 10.7, 22.6, 21.2, 20.2,
       23.7,  5.5, 13.2, 23.8, 18.4,  8.1, 24.2, 20.7, 14. , 16. , 11.3,
       11. , 13.4, 18.9, 22.3, 18.3, 12.4,  8.8, 11. , 17. ,  8.7,  6.9,
       14.2,  5.3, 11. , 11.8, 17.3, 11.3, 13.6, 21.7, 20.2, 12. , 16. ,
       12.9, 16.7, 14. ,  7.3, 19.4, 22.2, 11.5, 16.9, 16.7, 20.5, 25.4,
       17.2, 16.7, 23.8, 19.8, 19.7, 20.7, 15. ,  7.2, 12. ,  5.3, 19.8,
       18.4, 21.8, 17.1, 20.9, 14.6, 12.6, 12.2,  9.4, 15.9,  6.6, 15.5,
        7. , 16.6, 15.2, 19.7, 10.6,  6.6, 11.9, 24.7,  9.7,  1.6, 17.7,
        5.7, 19.6, 10.8, 11.6,  9.5, 20.8,  9.6, 20.7, 10.9, 19.2, 20.1,
       10.4, 12.3, 10.3, 18.2, 25.4, 10.9, 10.1, 16

In [74]:
res = np.sum(np.where(sales >=20, 1, 0))
res

40

In [76]:
sales

array([22.1, 10.4, 12. , 16.5, 17.9,  7.2, 11.8, 13.2,  4.8, 15.6, 12.6,
       17.4,  9.2, 13.7, 19. , 22.4, 12.5, 24.4, 11.3, 14.6, 18. , 17.5,
        5.6, 20.5,  9.7, 17. , 15. , 20.9, 18.9, 10.5, 21.4, 11.9, 13.2,
       17.4, 11.9, 17.8, 25.4, 14.7, 10.1, 21.5, 16.6, 17.1, 20.7, 17.9,
        8.5, 16.1, 10.6, 23.2, 19.8,  9.7, 16.4, 10.7, 22.6, 21.2, 20.2,
       23.7,  5.5, 13.2, 23.8, 18.4,  8.1, 24.2, 20.7, 14. , 16. , 11.3,
       11. , 13.4, 18.9, 22.3, 18.3, 12.4,  8.8, 11. , 17. ,  8.7,  6.9,
       14.2,  5.3, 11. , 11.8, 17.3, 11.3, 13.6, 21.7, 20.2, 12. , 16. ,
       12.9, 16.7, 14. ,  7.3, 19.4, 22.2, 11.5, 16.9, 16.7, 20.5, 25.4,
       17.2, 16.7, 23.8, 19.8, 19.7, 20.7, 15. ,  7.2, 12. ,  5.3, 19.8,
       18.4, 21.8, 17.1, 20.9, 14.6, 12.6, 12.2,  9.4, 15.9,  6.6, 15.5,
        7. , 16.6, 15.2, 19.7, 10.6,  6.6, 11.9, 24.7,  9.7,  1.6, 17.7,
        5.7, 19.6, 10.8, 11.6,  9.5, 20.8,  9.6, 20.7, 10.9, 19.2, 20.1,
       10.4, 12.3, 10.3, 18.2, 25.4, 10.9, 10.1, 16

In [88]:
keys

['TV', 'Radio', 'Newspaper', 'Sales']

In [89]:
sale_id = keys.index('Sales')
news_id = keys.index('Newspaper')
news_avg = np.average(data[:, news_id])
right_data = data[data[:,news_id]>news_avg]
s = np.sum(right_data[:, sale_id])
s

1405.1

In [107]:
sales = data[:, keys.index('Sales')]
avg_sale = np.average(sales)
scores = np.full(sales.shape, fill_value='Bad', dtype='<U8')
for i in range(sales.shape[0]):
    if sales[i]>avg_sale:
        scores[i] = 'Good'
    elif sales[i] == avg_sale:
        scores[i] = 'Average'

In [108]:
scores

array(['Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Bad', 'Bad', 'Bad',
       'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Good',
       'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Good', 'Bad', 'Good', 'Bad',
       'Good', 'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Bad', 'Good',
       'Good', 'Bad', 'Bad', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Bad', 'Good', 'Bad', 'Good', 'Good', 'Bad', 'Good', 'Bad', 'Good',
       'Good', 'Good', 'Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad',
       'Good', 'Good', 'Bad', 'Good', 'Bad', 'Bad', 'Bad', 'Good', 'Good',
       'Good', 'Bad', 'Bad', 'Bad', 'Good', 'Bad', 'Bad', 'Bad', 'Bad',
       'Bad', 'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Good',
       'Bad', 'Good', 'Bad', 'Bad', 'Good', 'Good', 'Bad', 'Good', 'Good',
       'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Bad', 'Bad', 'Bad', 'Bad', 'Good', 'Good', 'Good', 'Good', 'Good',
       'Bad', 'Bad', 'Bad', 'Bad', 'Good', 'Bad',

In [98]:
sales.shape[0]

200