In [3]:
import numpy as np

# Define the dataset as a list of lists
data = [
    [805, 51000, 1],
    [780, 49500, 1],
    [795, 52000, 1],
    [820, 50500, 1],
    [810, 48000, 1],
    [785, 53000, 1],
    [815, 49000, 1],
    [800, 50000, 1],
    [610, 31000, 0],
    [590, 28000, 0],
    [620, 33000, 0],
    [580, 29000, 0],
    [600, 32000, 0],
    [595, 27000, 0],
    [605, 34000, 0],
    [585, 31500, 0]
]

# Convert the list of lists to a numpy array
data = np.array(data)

In [40]:
x10 = data[data[:, 2] == 1][:, 0]
x11 = data[data[:, 2] == 1][:, 1]
x00 = data[data[:, 2] == 0][:, 0]
x01 = data[data[:, 2] == 0][:, 1]

In [44]:
import numpy as np
from scipy.stats import norm

# Thông tin phân phối cho lớp "Đạt"
mean_lumen_achieved = x10.mean()
std_lumen_achieved = x10.std()
mean_lifetime_achieved = x11.mean()
std_lifetime_achieved = x11.std()

# Thông tin phân phối cho lớp "Không đạt"
mean_lumen_not_achieved = x00.mean()
std_lumen_not_achieved = x00.std()
mean_lifetime_not_achieved = x01.mean()
std_lifetime_not_achieved = x01.std()

# Xác suất của các lớp
prob_achieved = 8 / 16  # Số bóng đèn "Đạt" / Tổng số bóng đèn
prob_not_achieved = 8 / 16  # Số bóng đèn "Không đạt" / Tổng số bóng đèn

# Dữ liệu của bóng đèn cần phân loại
lumen = 750
lifetime = 45000

# Calculate conditional probabilities
p_lumen_given_achieved = norm.pdf(
    lumen, mean_lumen_achieved, std_lumen_achieved)
p_lifetime_given_achieved = norm.pdf(
    lifetime, mean_lifetime_achieved, std_lifetime_achieved)
p_achieved = prob_achieved * p_lumen_given_achieved * p_lifetime_given_achieved

p_lumen_given_not_achieved = norm.pdf(
    lumen, mean_lumen_not_achieved, std_lumen_not_achieved)
p_lifetime_given_not_achieved = norm.pdf(
    lifetime, mean_lifetime_not_achieved, std_lifetime_not_achieved)
p_not_achieved = prob_not_achieved * \
    p_lumen_given_not_achieved * p_lifetime_given_not_achieved

# Logarithmic transformation
log_p_achieved = np.log10(p_achieved)
log_p_not_achieved = np.log10(p_not_achieved)

# Display results
print(f"Log of unnormalized probability for 'Đạt': {log_p_achieved:.6f}")
print(f"Log of unnormalized probability for 'Không đạt': {
      log_p_not_achieved:.6f}")

# Normalize probabilities
total = p_achieved + p_not_achieved
p_achieved_normalized = p_achieved / total
p_not_achieved_normalized = p_not_achieved / total

print(f"Normalized probability for 'Đạt': {p_achieved_normalized:.12f}")
print(f"Normalized probability for 'Không đạt': {
      p_not_achieved_normalized:.6f}")

Log of unnormalized probability for 'Đạt': -11.419187
Log of unnormalized probability for 'Không đạt': -46.073488
Normalized probability for 'Đạt': 1.000000000000
Normalized probability for 'Không đạt': 0.000000


# Problem 45:


In [47]:
X = np.array([-2, 7, 3, 0, 6, 1, -3, 6, 5, -3])

In [49]:
X.mean()

2.0

# Problem 46:


In [51]:
X = np.array([7, 0, 9, 2, 5, 7])

In [53]:
np.median(X)

6.0

# Problem 47:


In [60]:
X = np.array([84, 30, 26, 85, 40, 69, 28, 28, 85, 33, 81, 29, 9, 24, 3])

In [61]:
X.std()**2

776.9066666666666

In [62]:
X.std()

27.87304552191358

# Problem 48


In [66]:
X1 = np.array([50, 53, 97, 45, 81, 61, 87, 66, 9, 34])
Y1 = np.array([18, 46, 4, 54, 40, 32, 36, 2, 25, 19])

X2 = np.array([13, 42, 17, 2, 83, 57, 19, 54, 19, 10])
Y2 = np.array([51, 85, 2, 97, 86, 60, 76, 83, 17, 61])

X3 = np.array([27, 38, 93, 60, 23, 10, 53, 46, 94, 3])
Y3 = np.array([6, 70, 3, 65, 61, 76, 15, 9, 4, 25])

X4 = np.array([23, 45, 77, 20, 89, 83, 87, 75, 56, 12])
Y4 = np.array([13, 53, 62, 54, 57, 27, 29, 46, 79, 5])

# Calculate Pearson correlation coefficients
cor_X1_Y1 = np.corrcoef(X1, Y1)[0, 1]
cor_X2_Y2 = np.corrcoef(X2, Y2)[0, 1]
cor_X3_Y3 = np.corrcoef(X3, Y3)[0, 1]
cor_X4_Y4 = np.corrcoef(X4, Y4)[0, 1]

print(f"X1 and Y1: {cor_X1_Y1:.2f}")
print(f"X2 and Y2: {cor_X2_Y2:.2f}")
print(f"X3 and Y3: {cor_X3_Y3:.2f}")
print(f"X4 and Y4: {cor_X4_Y4:.2f}")

X1 and Y1: -0.15
X2 and Y2: 0.32
X3 and Y3: -0.47
X4 and Y4: 0.35


In [69]:
import numpy as np

# Define the vectors
v1, u1 = np.array([1, 2, 3, 4]), np.array([3, 4, 5, 6])
v2, u2 = np.array([5, 6, 7]), np.array([2, 3])
v3, u3 = np.array([-1, 2, -3]), np.array([4, -5, 6])
v4, u4 = np.array([4, 2, 3]), np.array([4, 5, 6])

# Calculate the dot products
dot_product_1 = np.dot(v1, u1)
# dot_product_2 = np.dot(v2, u2)
dot_product_3 = np.dot(v3, u3)
dot_product_4 = np.dot(v4, u4)

print(f"Dot product for v1 and u1: {dot_product_1}")
# print(f"Dot product for v2 and u2: {dot_product_2}")
print(f"Dot product for v3 and u3: {dot_product_3}")
print(f"Dot product for v4 and u4: {dot_product_4}")

Dot product for v1 and u1: 50
Dot product for v3 and u3: -32
Dot product for v4 and u4: 44


In [70]:
import numpy as np

# Case (a)
A_a = np.array([[8, 8, 1], [2, 7, 1]])
B_a = np.array([[8, 1], [7, 1], [2, 8]])

result_a = np.dot(A_a, B_a)
print("Case (a) Result:\n", result_a)

# Case (b)
A_b = np.array([[1, 2], [3, 4]])
B_b = np.array([[5, 6], [7, 8]])

result_b = np.dot(A_b, B_b)
print("Case (b) Result:\n", result_b)

# Case (c)
A_c = np.array([[5, 2], [3, 4]])
B_c = np.array([[5, 6], [7, 8], [3, 4]])

# Check dimensions
if A_c.shape[1] == B_c.shape[0]:
    result_c = np.dot(A_c, B_c)
    print("Case (c) Result:\n", result_c)
    print("Matches C_c:", np.array_equal(result_c, C_c))
else:
    print("Case (c) Matrix dimensions mismatch")

# Case (d)
A_d = np.array([[1, 2, 3], [4, 5, 6]])
B_d = np.array([[7, 8], [9, 10], [11, 12]])

result_d = np.dot(A_d, B_d)
print("Case (d) Result:\n", result_d)

Case (a) Result:
 [[122  24]
 [ 67  17]]
Case (b) Result:
 [[19 22]
 [43 50]]
Case (c) Matrix dimensions mismatch
Case (d) Result:
 [[ 58  64]
 [139 154]]


In [81]:
import numpy as np

# Define the matrix
matrix = np.array([[0, 1], [1, 0]])

# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Print the results
print("Eigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[ 1. -1.]

Eigenvectors:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [82]:
import numpy as np

# Case (a)
A_a = np.array([[1, 4], [3, 2]])
eigenvalues_a, eigenvectors_a = np.linalg.eig(A_a)
print("Case (a) Eigenvalues:\n", eigenvalues_a)
print("Case (a) Eigenvectors:\n", eigenvectors_a)

# Case (b)
A_b = np.array([[2, 1], [1, 2]])
eigenvalues_b, eigenvectors_b = np.linalg.eig(A_b)
print("Case (b) Eigenvalues:\n", eigenvalues_b)
print("Case (b) Eigenvectors:\n", eigenvectors_b)

# Case (c)
A_c = np.array([[0, 1], [1, 0]])
eigenvalues_c, eigenvectors_c = np.linalg.eig(A_c)
print("Case (c) Eigenvalues:\n", eigenvalues_c)
print("Case (c) Eigenvectors:\n", eigenvectors_c)

# Case (d)
A_d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
eigenvalues_d, eigenvectors_d = np.linalg.eig(A_d)
print("Case (d) Eigenvalues:\n", eigenvalues_d)
print("Case (d) Eigenvectors:\n", eigenvectors_d)

Case (a) Eigenvalues:
 [-2.  5.]
Case (a) Eigenvectors:
 [[-0.8        -0.70710678]
 [ 0.6        -0.70710678]]
Case (b) Eigenvalues:
 [3. 1.]
Case (b) Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Case (c) Eigenvalues:
 [ 1. -1.]
Case (c) Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
Case (d) Eigenvalues:
 [ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
Case (d) Eigenvectors:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [ ]:
import math


class Solution:
    def calculate_eigenvalues_eigenvectors(self, A):
        def get_eigenvalues(matrix):
            det = matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
            a, b, c, d = matrix[0][0], matrix[0][1], matrix[1][0], matrix[1][1]
            trace = a + d
            eigenvalue1 = (trace + (trace**2 - 4*det)**0.5) / 2
            eigenvalue2 = (trace - (trace**2 - 4*det)**0.5) / 2

            return eigenvalue1, eigenvalue2

        def get_eigenvectors(matrix, eigenvalue):
            _, eigenvectors = np.linalg.eig(matrix)
            eigenvector1, eigenvector2 = eigenvectors[0], eigenvectors[1]
            return eigenvector1, eigenvector2
        A = np.array(A)
        eigenvalue1, eigenvalue2 = get_eigenvalues(A)
        eigenvalues = (eigenvalue1, eigenvalue2)
        eigenvector1, eigenvector2 = get_eigenvectors(A, eigenvalues)

        return {eigenvalue1: eigenvector1, eigenvalue2: eigenvector2}

In [88]:
def get_eigenvalues(matrix):
    det = matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    a, b, c, d = matrix[0][0], matrix[0][1], matrix[1][0], matrix[1][1]
    trace = a + d
    eigenvalue1 = (trace + (trace**2 - 4*det)**0.5) / 2
    eigenvalue2 = (trace - (trace**2 - 4*det)**0.5) / 2
    return [eigenvalue1, eigenvalue2]

A = [[1,4], [3, 2]]
B = get_eigenvalues(A)

In [85]:
import math

In [108]:
def get_eigenvectors(matrix, eigenvalues):
    def cal (matrix, eigenvalue):
        lam = eigenvalue
        print(lam)
        a, b, c, d = float(matrix[0][0]-lam), float( matrix[0][1]), float( matrix[1][0]), float(matrix[1][1]-lam)
        eigenvector = [-a/b, 1.0]
        if eigenvector[0] < 0:
            eigenvector = [eigenvector[0]*(-1), eigenvector[0]*(-1)]
        len = math.sqrt( eigenvector[0]**2 + eigenvector[1]**2)
        print('eigenvector', eigenvector)
        print('len', len)

        eigenvector = [eigenvector[0]/len, eigenvector[1]/len]
        return eigenvector
    eigenvector1 = cal(matrix, eigenvalues[0])
    eigenvector2 = cal(matrix, eigenvalues[1])

    return eigenvector1, eigenvector2

In [109]:
get_eigenvectors(A, B)

5.0
eigenvector [1.0, 1.0]
len 1.4142135623730951
-2.0
eigenvector [0.75, 0.75]
len 1.0606601717798212


([0.7071067811865475, 0.7071067811865475],
 [0.7071067811865476, 0.7071067811865476])

In [113]:
import math
import numpy as np


class Solution:
    def calculate_eigenvalues_eigenvectors(self, A):
        def get_eigenvalues(matrix):
            det = matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
            a, b, c, d = matrix[0][0], matrix[0][1], matrix[1][0], matrix[1][1]
            trace = a + d
            eigenvalue1 = (trace + (trace**2 - 4*det)**0.5) / 2
            eigenvalue2 = (trace - (trace**2 - 4*det)**0.5) / 2
            return eigenvalue1, eigenvalue2

        def get_eigenvectors(matrix, eigenvalues):
            def cal (matrix, eigenvalue):
                lam = eigenvalue
                print(lam)
                a, b, c, d = float(matrix[0][0]-lam), float( matrix[0][1]), float( matrix[1][0]), float(matrix[1][1]-lam)
                eigenvector = [-a/b, 1.0]
                if eigenvector[0] > 0:
                    eigenvector = [eigenvector[0]*(-1), eigenvector[0]*(-1)]
                len = math.sqrt( eigenvector[0]**2 + eigenvector[1]**2)
                print('eigenvector', eigenvector)
                print('len', len)

                eigenvector = [eigenvector[0]/len, eigenvector[1]/len]
                return eigenvector
            eigenvector1 = cal(matrix, eigenvalues[0])
            eigenvector2 = cal(matrix, eigenvalues[1])

            return eigenvector1, eigenvector2
    
        eigenvalues = get_eigenvalues(A)
        eigenvectors = get_eigenvectors(A, eigenvalues)
        eigenvalue1, eigenvalue2 = eigenvalues
        eigenvector1, eigenvector2 = eigenvectors 

        return {eigenvalue1: eigenvector1, eigenvalue2: eigenvector2}

In [114]:
B = Solution()
B.calculate_eigenvalues_eigenvectors(A)

5.0
eigenvector [-1.0, -1.0]
len 1.4142135623730951
-2.0
eigenvector [-0.75, 1.0]
len 1.25


{5.0: [-0.7071067811865475, -0.7071067811865475], -2.0: [-0.6, 0.8]}

In [115]:
class Solution:
    def calculate_cosine_similarity(self, X, Y):
        if len(X) != len(Y):
            return -1
        num = sum(x * y for x, y in zip(X, Y))
        len_X = math.sqrt(sum(x ** 2 for x in X))
        len_Y = math.sqrt(sum(y ** 2 for y in Y))
        den = len_X*len_Y
        return num/den

        pass

In [3]:
import torch

In [4]:
torch.cuda.is_available()

False