In [ ]:
import numpy as np


In [ ]:
def fw (W):
    W = np.array(W)
    coff = np.array([0.1, 2])
    return np.sum(coff*W**2)


# 1. Gradient Descent


In [43]:
def df_w(W):
    W = np.array(W)
    coff = np.array([0.1, 2])
    return 2*coff*W


In [ ]:
def sgd(W, dW, lr):
    W = W - lr*dW
    return W


In [ ]:
# Example
def train_p1_1(optimizer, lr, epochs):
    W = np.array([-5,-2], dtype=np.float64)
    results = [W]
    for i in range(epochs):
        dW = df_w(W)
        W =optimizer(W, dW, lr)
        results.append(W)
        print("Epoch: {:>2}: W = {}".format(i + 1, W))
    return results

epoch = 30
lr = 0.4
train_p1_1(sgd, lr, epoch)


Epoch:  1: W = [-4.6  1.2]
Epoch:  2: W = [-4.232 -0.72 ]
Epoch:  3: W = [-3.89344  0.432  ]
Epoch:  4: W = [-3.5819648 -0.2592   ]
Epoch:  5: W = [-3.29540762  0.15552   ]
Epoch:  6: W = [-3.03177501 -0.093312  ]
Epoch:  7: W = [-2.78923301  0.0559872 ]
Epoch:  8: W = [-2.56609437 -0.03359232]
Epoch:  9: W = [-2.36080682  0.02015539]
Epoch: 10: W = [-2.17194227 -0.01209324]
Epoch: 11: W = [-1.99818689  0.00725594]
Epoch: 12: W = [-1.83833194 -0.00435356]
Epoch: 13: W = [-1.69126538  0.00261214]
Epoch: 14: W = [-1.55596415 -0.00156728]
Epoch: 15: W = [-1.43148702e+00  9.40369969e-04]
Epoch: 16: W = [-1.31696806e+00 -5.64221981e-04]
Epoch: 17: W = [-1.21161061e+00  3.38533189e-04]
Epoch: 18: W = [-1.11468176e+00 -2.03119913e-04]
Epoch: 19: W = [-1.02550722e+00  1.21871948e-04]
Epoch: 20: W = [-9.43466646e-01 -7.31231688e-05]
Epoch: 21: W = [-8.67989314e-01  4.38739013e-05]
Epoch: 22: W = [-7.98550169e-01 -2.63243408e-05]
Epoch: 23: W = [-7.34666155e-01  1.57946045e-05]
Epoch: 24: W = [-

[array([-5., -2.]),
 array([-4.6,  1.2]),
 array([-4.232, -0.72 ]),
 array([-3.89344,  0.432  ]),
 array([-3.5819648, -0.2592   ]),
 array([-3.29540762,  0.15552   ]),
 array([-3.03177501, -0.093312  ]),
 array([-2.78923301,  0.0559872 ]),
 array([-2.56609437, -0.03359232]),
 array([-2.36080682,  0.02015539]),
 array([-2.17194227, -0.01209324]),
 array([-1.99818689,  0.00725594]),
 array([-1.83833194, -0.00435356]),
 array([-1.69126538,  0.00261214]),
 array([-1.55596415, -0.00156728]),
 array([-1.43148702e+00,  9.40369969e-04]),
 array([-1.31696806e+00, -5.64221981e-04]),
 array([-1.21161061e+00,  3.38533189e-04]),
 array([-1.11468176e+00, -2.03119913e-04]),
 array([-1.02550722e+00,  1.21871948e-04]),
 array([-9.43466646e-01, -7.31231688e-05]),
 array([-8.67989314e-01,  4.38739013e-05]),
 array([-7.98550169e-01, -2.63243408e-05]),
 array([-7.34666155e-01,  1.57946045e-05]),
 array([-6.75892863e-01, -9.47676268e-06]),
 array([-6.21821434e-01,  5.68605761e-06]),
 array([-5.72075719e-01,

# 2. Gradient Descent + Momentum


In [ ]:
def sgd_momentum(W, dW, lr, V, beta):
    V = np.array(beta*V + (1-beta)*dW)
    W = np.array(W - lr*V)
    return W, V


In [ ]:
# Example
def train_p1_2(optimizer, lr, epochs, beta):
    W = np.array([-5,-2], dtype=np.float64)
    results = [W]
    V = np.zeros_like(W)
    for i in range(epochs):
        dW = df_w(W)
        W, V =optimizer(W, dW, lr, V, beta)
        results.append(W)
        print("Epoch: {:>2}: W = {}".format(i+1, W))
    return results

epoch = 30
lr = 0.6
beta = 0.5

train_p1_2(sgd_momentum, lr, epoch, beta)


Epoch:  1: W = [-4.7  0.4]
Epoch:  2: W = [-4.268  1.12 ]
Epoch:  3: W = [-3.79592  0.136  ]
Epoch:  4: W = [-3.3321248 -0.5192   ]
Epoch:  5: W = [-2.90029971 -0.22376   ]
Epoch:  6: W = [-2.51036919  0.192472  ]
Epoch:  7: W = [-2.16478177  0.1696216 ]
Epoch:  8: W = [-1.86210116 -0.04534952]
Epoch:  9: W = [-1.59903478 -0.09841566]
Epoch: 10: W = [-1.37155951 -0.00684994]
Epoch: 11: W = [-1.1755283   0.04715285]
Epoch: 12: W = [-1.006981    0.01757082]
Epoch: 13: W = [-0.86228849 -0.01830518]
Epoch: 14: W = [-0.73820492 -0.01427696]
Epoch: 15: W = [-0.63187084  0.0048695 ]
Epoch: 16: W = [-0.54079155  0.00859933]
Epoch: 17: W = [-4.62804416e-01  1.45050014e-04]
Epoch: 18: W = [-0.39604258 -0.00425615]
Epoch: 19: W = [-0.33889911 -0.00134937]
Epoch: 20: W = [-0.28999343  0.00172326]
Epoch: 21: W = [-0.24814098  0.00119166]
Epoch: 22: W = [-0.2123263  -0.00050413]
Epoch: 23: W = [-0.18167938 -0.00074707]
Epoch: 24: W = [-1.55455157e-01  2.79448010e-05]
Epoch: 25: W = [-0.13301574  0.0

[array([-5., -2.]),
 array([-4.7,  0.4]),
 array([-4.268,  1.12 ]),
 array([-3.79592,  0.136  ]),
 array([-3.3321248, -0.5192   ]),
 array([-2.90029971, -0.22376   ]),
 array([-2.51036919,  0.192472  ]),
 array([-2.16478177,  0.1696216 ]),
 array([-1.86210116, -0.04534952]),
 array([-1.59903478, -0.09841566]),
 array([-1.37155951, -0.00684994]),
 array([-1.1755283 ,  0.04715285]),
 array([-1.006981  ,  0.01757082]),
 array([-0.86228849, -0.01830518]),
 array([-0.73820492, -0.01427696]),
 array([-0.63187084,  0.0048695 ]),
 array([-0.54079155,  0.00859933]),
 array([-4.62804416e-01,  1.45050014e-04]),
 array([-0.39604258, -0.00425615]),
 array([-0.33889911, -0.00134937]),
 array([-0.28999343,  0.00172326]),
 array([-0.24814098,  0.00119166]),
 array([-0.2123263 , -0.00050413]),
 array([-0.18167938, -0.00074707]),
 array([-1.55455157e-01,  2.79448010e-05]),
 array([-0.13301574,  0.00038192]),
 array([-1.13815082e-01,  1.00603444e-04]),
 array([-0.09738585, -0.00016078]),
 array([-8.33280

# 3. RMSProb


In [ ]:
def RMSProp(W, dW, lr, S, gamma):
    epsilon = 1e-6
    S = np.array(gamma*S + (1-gamma)*dW**2)
    W = np.array(W - lr*dW/np.sqrt(S + epsilon))
    return W, S


In [ ]:
def train_p1_3(optimizer, lr, epochs, gamma):
    W = np.array([-5,-2], dtype=np.float64)
    results = [W]
    S = np.zeros_like(W)
    for i in range(epochs):
        dW = df_w(W)
        W, S =optimizer(W, dW, lr, S, gamma)
        results.append(W)
        print("Epoch: {:>2}: W = {}".format(i + 1, W))
    return results

epoch = 30
lr = 0.3
gamma = 0.9
train_p1_3(RMSProp, lr, epoch, gamma)


Epoch:  1: W = [-4.05132145 -1.05131678]
Epoch:  2: W = [-3.43519754 -0.59152343]
Epoch:  3: W = [-2.95893693 -0.3294394 ]
Epoch:  4: W = [-2.56546289 -0.17756482]
Epoch:  5: W = [-2.22920552 -0.09163256]
Epoch:  6: W = [-1.93626752 -0.04494499]
Epoch:  7: W = [-1.67817686 -0.02081423]
Epoch:  8: W = [-1.44934985 -0.00903559]
Epoch:  9: W = [-1.24588199 -0.00364591]
Epoch: 10: W = [-1.06490301 -0.00135351]
Epoch: 11: W = [-9.04202260e-01 -4.56444431e-04]
Epoch: 12: W = [-7.61996495e-01 -1.37562928e-04]
Epoch: 13: W = [-6.36778499e-01 -3.62601019e-05]
Epoch: 14: W = [-5.27215237e-01 -8.11337456e-06]
Epoch: 15: W = [-4.32078505e-01 -1.47473412e-06]
Epoch: 16: W = [-3.50198507e-01 -2.02783991e-07]
Epoch: 17: W = [-2.80434649e-01 -1.84231187e-08]
Epoch: 18: W = [-2.21659834e-01 -7.67742748e-10]
Epoch: 19: W = [-1.72755512e-01  7.80451998e-12]
Epoch: 20: W = [-1.32615134e-01 -5.05794800e-13]
Epoch: 21: W = [-1.00153779e-01  6.19123501e-14]
Epoch: 22: W = [-7.43217708e-02 -1.13373781e-14]
Ep

[array([-5., -2.]),
 array([-4.05132145, -1.05131678]),
 array([-3.43519754, -0.59152343]),
 array([-2.95893693, -0.3294394 ]),
 array([-2.56546289, -0.17756482]),
 array([-2.22920552, -0.09163256]),
 array([-1.93626752, -0.04494499]),
 array([-1.67817686, -0.02081423]),
 array([-1.44934985, -0.00903559]),
 array([-1.24588199, -0.00364591]),
 array([-1.06490301, -0.00135351]),
 array([-9.04202260e-01, -4.56444431e-04]),
 array([-7.61996495e-01, -1.37562928e-04]),
 array([-6.36778499e-01, -3.62601019e-05]),
 array([-5.27215237e-01, -8.11337456e-06]),
 array([-4.32078505e-01, -1.47473412e-06]),
 array([-3.50198507e-01, -2.02783991e-07]),
 array([-2.80434649e-01, -1.84231187e-08]),
 array([-2.21659834e-01, -7.67742748e-10]),
 array([-1.72755512e-01,  7.80451998e-12]),
 array([-1.32615134e-01, -5.05794800e-13]),
 array([-1.00153779e-01,  6.19123501e-14]),
 array([-7.43217708e-02, -1.13373781e-14]),
 array([-5.41201278e-02,  2.80166702e-15]),
 array([-3.86159157e-02, -8.81341191e-16]),
 arr

# 4. Adam


In [ ]:
def Adam(W, dW, lr, V, S, beta1, beta2, t):

    epsilon = 1e-6
    V = np.array(beta1*V + (1-beta1)*dW)
    S = np.array(beta2*S + (1-beta2)*dW**2)
    V_hat = V/(1-beta1**t)
    S_hat = S/(1-beta2**t)
    W = np.array(W - lr*V_hat/np.sqrt(S_hat + epsilon))
    return W, V, S


In [ ]:
def train_p1_4(optimizer, lr, epochs, beta1, beta2):
    W = np.array([-5,-2], dtype=np.float64)
    results = [W]
    V = np.zeros_like(W)
    S = np.zeros_like(W)
    for i in range(epochs):
        dW = df_w(W)
        W, V, S =optimizer(W, dW, lr, V, S, beta1, beta2, i+1)
        results.append(W)
        print("Epoch: {:>2}: W = {}".format(i+1, W))
    return results

epoch = 30
lr = 0.2
beta1 = 0.9
beta2 = 0.999
train_p1_4(Adam, lr, epoch, beta1, beta2)


Epoch:  1: W = [-4.8000001 -1.8      ]
Epoch:  2: W = [-4.60025458 -1.60082446]
Epoch:  3: W = [-4.40094818 -1.40317255]
Epoch:  4: W = [-4.20227724 -1.20787812]
Epoch:  5: W = [-4.00444983 -1.01592732]
Epoch:  6: W = [-3.80768579 -0.82847292]
Epoch:  7: W = [-3.61221664 -0.64684142]
Epoch:  8: W = [-3.41828545 -0.47252746]
Epoch:  9: W = [-3.22614653 -0.30716913]
Epoch: 10: W = [-3.03606497 -0.15249832]
Epoch: 11: W = [-2.84831603 -0.01026302]
Epoch: 12: W = [-2.66318433  0.11787577]
Epoch: 13: W = [-2.48096283  0.23046186]
Epoch: 14: W = [-2.30195156  0.32635894]
Epoch: 15: W = [-2.12645613  0.40484216]
Epoch: 16: W = [-1.95478597  0.46564981]
Epoch: 17: W = [-1.7872523   0.50898816]
Epoch: 18: W = [-1.62416583  0.53549455]
Epoch: 19: W = [-1.46583419  0.54617153]
Epoch: 20: W = [-1.31255919  0.54230818]
Epoch: 21: W = [-1.16463376  0.52540208]
Epoch: 22: W = [-1.02233886  0.49709058]
Epoch: 23: W = [-0.88594013  0.45909505]
Epoch: 24: W = [-0.75568468  0.41317772]
Epoch: 25: W = [-0

[array([-5., -2.]),
 array([-4.8000001, -1.8      ]),
 array([-4.60025458, -1.60082446]),
 array([-4.40094818, -1.40317255]),
 array([-4.20227724, -1.20787812]),
 array([-4.00444983, -1.01592732]),
 array([-3.80768579, -0.82847292]),
 array([-3.61221664, -0.64684142]),
 array([-3.41828545, -0.47252746]),
 array([-3.22614653, -0.30716913]),
 array([-3.03606497, -0.15249832]),
 array([-2.84831603, -0.01026302]),
 array([-2.66318433,  0.11787577]),
 array([-2.48096283,  0.23046186]),
 array([-2.30195156,  0.32635894]),
 array([-2.12645613,  0.40484216]),
 array([-1.95478597,  0.46564981]),
 array([-1.7872523 ,  0.50898816]),
 array([-1.62416583,  0.53549455]),
 array([-1.46583419,  0.54617153]),
 array([-1.31255919,  0.54230818]),
 array([-1.16463376,  0.52540208]),
 array([-1.02233886,  0.49709058]),
 array([-0.88594013,  0.45909505]),
 array([-0.75568468,  0.41317772]),
 array([-0.63179773,  0.36110878]),
 array([-0.51447945,  0.30464032]),
 array([-0.40390206,  0.2454839 ]),
 array([-0